<?php

/**
 * Created by PhpStorm.
 * User: Nguyen Thanh
 * Date: 11/19/2016
 * Time: 4:33 PM
 */
class Socialcommerce_Form_Admin_Faqs_Edit extends Socialcommerce_Form_Admin_Faqs_Create
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        $this->setTitle('Edit Faq')->setDescription('');

        $this->submit->setLabel('Save Changes');
    }

}