<?php

/**
 * Created by PhpStorm.
 * socialcommerce: Nguyen Thanh
 * Date: 10/13/2016
 * Time: 9:10 PM
 */
class Socialcommerce_Installer extends Engine_Package_Installer_Module
{
    public function onInstall()
    {
        $this->_addCreateNewStallStep1Page();
        $this->_addCreateNewStallStep2Page();
        $this->_addStallBrowsePages();
        $this->_addCreateNewProduct();
        $this->_addStallDetailPage();
        return parent::onInstall(); // TODO: Change the autogenerated stub
    }

    protected function _addStallBrowsePages()
    {
        $db = $this->getDb();

        // member browse page
        $page_id = $db->select()
            ->from('engine4_core_pages', 'page_id')
            ->where('name = ?', 'socialcommerce_stall_browse')
            ->limit(1)
            ->query()
            ->fetchColumn();

        // insert if it doesn't exist yet
        if( !$page_id ) {
            // Insert page
            $db->insert('engine4_core_pages', array(
                'name' => 'socialcommerce_stall_browse',
                'displayname' => 'Social Commerce Stall Browse Page',
                'title' => 'Stall Browse',
                'description' => 'This page show stall lists.',
                'custom' => 0,
            ));
            $page_id = $db->lastInsertId();

            // Insert top
            $db->insert('engine4_core_content', array(
                'type' => 'container',
                'name' => 'top',
                'page_id' => $page_id,
                'order' => 1,
            ));
            $top_id = $db->lastInsertId();

            // Insert main
            $db->insert('engine4_core_content', array(
                'type' => 'container',
                'name' => 'main',
                'page_id' => $page_id,
                'order' => 2,
            ));
            $main_id = $db->lastInsertId();

            // Insert top-middle
            $db->insert('engine4_core_content', array(
                'type' => 'container',
                'name' => 'middle',
                'page_id' => $page_id,
                'parent_content_id' => $top_id,
            ));
            $top_middle_id = $db->lastInsertId();

            // Insert main-middle
            $db->insert('engine4_core_content', array(
                'type' => 'container',
                'name' => 'middle',
                'page_id' => $page_id,
                'parent_content_id' => $main_id,
                'order' => 2,
            ));
            $main_middle_id = $db->lastInsertId();

            // Insert main-left
            $db->insert('engine4_core_content', array(
                'type' => 'container',
                'name' => 'left',
                'page_id' => $page_id,
                'parent_content_id' => $main_id,
                'order' => 1,
            ));
            $main_left_id = $db->lastInsertId();

            // Insert menu
            $db->insert('engine4_core_content', array(
                'type' => 'widget',
                'name' => 'socialcommerce.main-menu',
                'page_id' => $page_id,
                'parent_content_id' => $top_middle_id,
                'order' => 1,
            ));

            // Insert content
            $db->insert('engine4_core_content', array(
                'type' => 'widget',
                'name' => 'socialcommerce.stall-listings',
                'page_id' => $page_id,
                'parent_content_id' => $main_middle_id,
                'order' => 1,
            ));

            // Insert search
            $db->insert('engine4_core_content', array(
                'type' => 'widget',
                'name' => 'socialcommerce.browse-search',
                'page_id' => $page_id,
                'parent_content_id' => $main_left_id,
                'order' => 1,
            ));

            $db->insert('engine4_core_content', array(
                'type' => 'widget',
                'name' => 'socialcommerce.categories',
                'page_id' => $page_id,
                'parent_content_id' => $main_left_id,
                'order' => 2,
            ));
        }
    }

    protected function _addCreateNewProduct()
    {
        $db = $this->getDb();

        // profile page
        $page_id = $db->select()
            ->from('engine4_core_pages', 'page_id')
            ->where('name = ?', 'socialcommerce_product_create')
            ->limit(1)
            ->query()
            ->fetchColumn();

        if( !$page_id ) {

            // Insert page
            $db->insert('engine4_core_pages', array(
                'name' => 'socialcommerce_product_create',
                'displayname' => 'Social Commerce Product Create Page',
                'title' => 'Post a New Product',
                'description' => 'This page is the product create page.',
                'custom' => 0,
            ));
            $page_id = $db->lastInsertId();

            // Insert top
            $db->insert('engine4_core_content', array(
                'type' => 'container',
                'name' => 'top',
                'page_id' => $page_id,
                'order' => 1,
            ));
            $top_id = $db->lastInsertId();

            // Insert main
            $db->insert('engine4_core_content', array(
                'type' => 'container',
                'name' => 'main',
                'page_id' => $page_id,
                'order' => 2,
            ));
            $main_id = $db->lastInsertId();

            // Insert top-middle
            $db->insert('engine4_core_content', array(
                'type' => 'container',
                'name' => 'middle',
                'page_id' => $page_id,
                'parent_content_id' => $top_id,
            ));
            $top_middle_id = $db->lastInsertId();

            // Insert main-middle
            $db->insert('engine4_core_content', array(
                'type' => 'container',
                'name' => 'middle',
                'page_id' => $page_id,
                'parent_content_id' => $main_id,
                'order' => 2,
            ));
            $main_middle_id = $db->lastInsertId();

            // Insert menu
            $db->insert('engine4_core_content', array(
                'type' => 'widget',
                'name' => 'socialcommerce.main-menu',
                'page_id' => $page_id,
                'parent_content_id' => $top_middle_id,
                'order' => 1,
            ));

            // Insert content
            $db->insert('engine4_core_content', array(
                'type' => 'widget',
                'name' => 'core.content',
                'page_id' => $page_id,
                'parent_content_id' => $main_middle_id,
                'order' => 1,
            ));
        }
    }

    protected function _addStallDetailPage() {
        $db = $this->getDb();

        $page_id = $db->select()
            ->from('engine4_core_pages', 'page_id')
            ->where('name = ?', 'socialcommerce_stall_profile')
            ->limit(1)
            ->query()
            ->fetchColumn();

        if(!$page_id) {
            $db->insert('engine4_core_pages', array(
                'name' => 'socialcommerce_stall_profile',
                'displayname' => 'Social Commerce Stall Detail Page',
                'title' => 'Social Commerce Stall Detail Page',
                'description' => 'This page show the information of Stall',
                'custom' => 0
            ));
            $page_id = $db->lastInsertId();

            // Insert top
            $db->insert('engine4_core_content', array(
                'type' => 'container',
                'name' => 'top',
                'page_id' => $page_id,
                'order' => 1,
            ));
            $top_id = $db->lastInsertId();

            //Insert main
            $db->insert('engine4_core_content', array(
                'type' => 'container',
                'name' => 'main',
                'page_id' => $page_id,
                'order' => 2,
            ));
            $main_id = $db->lastInsertId();

            //Insert top-middle
            $db->insert('engine4_core_content', array(
                'type' => 'container',
                'name' => 'middle',
                'page_id' => $page_id,
                'parent_content_id' => $top_id,
            ));
            $top_middle_id = $db->lastInsertId();

            // Insert main-middle
            $db->insert('engine4_core_content', array(
                'type' => 'container',
                'name' => 'middle',
                'page_id' => $page_id,
                'parent_content_id' => $main_id,
                'order' => 2,
            ));
            $main_middle_id = $db->lastInsertId();

            //Insert main-right
            $db->insert('engine4_core_content', array(
                'type' => 'container',
                'name' => 'right',
                'page_id' => $page_id,
                'parent_content_id' => $main_id,
                'order' => 1,
            ));
            $main_right_id = $db->lastInsertId();

            //Insert menu
            $db->insert('engine4_core_content', array(
                'type' => 'widget',
                'name' => 'socialcommerce.main-menu',
                'page_id' => $page_id,
                'parent_content_id' => $top_middle_id,
                'order' => 1,
            ));

            //Insert cover style 2 widget
            $db->insert('engine4_core_content', array(
                'type' => 'widget',
                'name' => 'socialcommerce.stall-profile-cover',
                'page_id' => $page_id,
                'parent_content_id' => $top_middle_id,
                'order' => 2,
            ));

            // Insert tab container
            $db -> insert('engine4_core_content', array(
                'type' => 'widget',
                'name' => 'core.container-tabs',
                'page_id' => $page_id,
                'parent_content_id' => $main_middle_id,
                'order' => 2,
                'params' => '{"max":"6","title":"","nomobile":"0","name":"core.container-tabs"}',
            ));
            $main_container_id = $db -> lastInsertId();

            // Insert stalls may like widget
            $db -> insert('engine4_core_content', array(
                'type' => 'widget',
                'name' => 'socialcommerce.stall-profile-related-stalls',
                'page_id' => $page_id,
                'parent_content_id' => $main_middle_id,
                'order' => 3,
                'params' => '{"title":"Related Stalls"}',
            ));

            //Insert overview widget
            $db->insert('engine4_core_content', array(
                'type' => 'widget',
                'name' => 'socialcommerce.stall-profile-overview',
                'page_id' => $page_id,
                'parent_content_id' => $main_container_id,
                'order' => 1,
                'params' => '{"title":"Overview"}',
            ));

            //Insert activity widget
            $db->insert('engine4_core_content', array(
                'type' => 'widget',
                'name' => 'activity.feed',
                'page_id' => $page_id,
                'parent_content_id' => $main_container_id,
                'order' => 2,
                'params' => '{"title":"Activity"}',
            ));

            //Insert review widget
            $db->insert('engine4_core_content', array(
                'type' => 'widget',
                'name' => 'socialcommerce.stall-profile-reviews',
                'page_id' => $page_id,
                'parent_content_id' => $main_container_id,
                'order' => 3,
                'params' => '{"title":"Reviews", "titleCount": true}',
            ));

            //Insert contact us widget
            $db->insert('engine4_core_content', array(
                'type' => 'widget',
                'name' => 'socialcommerce.stall-profile-contact',
                'page_id' => $page_id,
                'parent_content_id' => $main_container_id,
                'order' => 4,
                'params' => '{"title":"Contact Us"}',
            ));

            //Insert profile blog widget
            $db->insert('engine4_core_content', array(
                'type' => 'widget',
                'name' => 'socialcommerce.stall-profile-blogs',
                'page_id' => $page_id,
                'parent_content_id' => $main_container_id,
                'order' => 5,
                'params' => '{"title":"Blogs", "titleCount": true}',
            ));

            //Insert profile event widget
            $db->insert('engine4_core_content', array(
                'type' => 'widget',
                'name' => 'socialcommerce.stall-profile-events',
                'page_id' => $page_id,
                'parent_content_id' => $main_container_id,
                'order' => 6,
                'params' => '{"title":"Events", "titleCount": true}',
            ));

            //Insert profile music widget
            $db->insert('engine4_core_content', array(
                'type' => 'widget',
                'name' => 'socialcommerce.stall-profile-musics',
                'page_id' => $page_id,
                'parent_content_id' => $main_container_id,
                'order' => 7,
                'params' => '{"title":"Musics", "titleCount": true}',
            ));

            //Insert profile photo widget
            $db->insert('engine4_core_content', array(
                'type' => 'widget',
                'name' => 'socialcommerce.stall-profile-photos',
                'page_id' => $page_id,
                'parent_content_id' => $main_container_id,
                'order' => 8,
                'params' => '{"title":"Photos", "titleCount": true}',
            ));

            //Insert profile video widget
            $db->insert('engine4_core_content', array(
                'type' => 'widget',
                'name' => 'socialcommerce.stall-profile-videos',
                'page_id' => $page_id,
                'parent_content_id' => $main_container_id,
                'order' => 9,
                'params' => '{"title":"Videos", "titleCount": true}',
            ));

            //Insert profile quick create link
            $db->insert('engine4_core_content', array(
                'type' => 'widget',
                'name' => 'socialcommerce.stall-create-link',
                'page_id' => $page_id,
                'parent_content_id' => $main_right_id,
                'order' => 1,
            ));

            //Insert profile operating hours widget
            $db->insert('engine4_core_content', array(
                'type' => 'widget',
                'name' => 'socialcommerce.stall-profile-operating-hours',
                'page_id' => $page_id,
                'parent_content_id' => $main_right_id,
                'order' => 2,
                'params' => '{"title":"Operating Hours"}',
            ));

            //Insert profile operating hours widget
            $db->insert('engine4_core_content', array(
                'type' => 'widget',
                'name' => 'socialcommerce.stall-profile-contact-info',
                'page_id' => $page_id,
                'parent_content_id' => $main_right_id,
                'order' => 3,
                'params' => '{"title":"Contact Information"}',
            ));

            //Insert profile check-in widget
            $db->insert('engine4_core_content', array(
                'type' => 'widget',
                'name' => 'socialcommerce.stall-profile-checkins',
                'page_id' => $page_id,
                'parent_content_id' => $main_right_id,
                'order' => 4,
            ));

            //Insert newest blogs widget
            $db->insert('engine4_core_content', array(
                'type' => 'widget',
                'name' => 'socialcommerce.stall-newest-blogs',
                'page_id' => $page_id,
                'parent_content_id' => $main_right_id,
                'order' => 5,
                'params' => '{"title":"Newest Blogs"}',
            ));

            //Insert newest events widget
            $db->insert('engine4_core_content', array(
                'type' => 'widget',
                'name' => 'socialcommerce.stall-newest-events',
                'page_id' => $page_id,
                'parent_content_id' => $main_right_id,
                'order' => 6,
                'params' => '{"title":"Newest Events"}',
            ));

            //Insert newest photos widget
            $db->insert('engine4_core_content', array(
                'type' => 'widget',
                'name' => 'socialcommerce.stall-newest-photos',
                'page_id' => $page_id,
                'parent_content_id' => $main_right_id,
                'order' => 7,
                'params' => '{"title":"Newest Photos"}',
            ));

            //Insert newest videos widget
            $db->insert('engine4_core_content', array(
                'type' => 'widget',
                'name' => 'socialcommerce.stall-newest-videos',
                'page_id' => $page_id,
                'parent_content_id' => $main_right_id,
                'order' => 8,
                'params' => '{"title":"Newest Videos"}',
            ));
        }
    }

    protected function _addCreateNewStallStep1Page()
    {
        $db = $this->getDb();

        $page_id = $db->select()
            ->from('engine4_core_pages', 'page_id')
            ->where('name = ?', 'socialcommerce_stall_create-step-one')
            ->limit(1)
            ->query()
            ->fetchColumn();

        if(!$page_id) {
            $db->insert('engine4_core_pages', array(
                'name' => 'socialcommerce_stall_create-step-one',
                'displayname' => 'Social Commerce Create a New Stall',
                'title' => 'Social Commerce Create a New Stall',
                'description' => 'Social Commerce Create a New Stall',
                'custom' => 0
            ));
            $page_id = $db->lastInsertId();

            // Insert top
            $db->insert('engine4_core_content', array(
                'type' => 'container',
                'name' => 'top',
                'page_id' => $page_id,
                'order' => 1,
            ));
            $top_id = $db->lastInsertId();

            //Insert main
            $db->insert('engine4_core_content', array(
                'type' => 'container',
                'name' => 'main',
                'page_id' => $page_id,
                'order' => 2,
            ));
            $main_id = $db->lastInsertId();

            //Insert top-middle
            $db->insert('engine4_core_content', array(
                'type' => 'container',
                'name' => 'middle',
                'page_id' => $page_id,
                'parent_content_id' => $top_id,
            ));
            $top_middle_id = $db->lastInsertId();

            // Insert main-middle
            $db->insert('engine4_core_content', array(
                'type' => 'container',
                'name' => 'middle',
                'page_id' => $page_id,
                'parent_content_id' => $main_id,
                'order' => 2,
            ));
            $main_middle_id = $db->lastInsertId();

            //Insert menu
            $db->insert('engine4_core_content', array(
                'type' => 'widget',
                'name' => 'socialcommerce.main-menu',
                'page_id' => $page_id,
                'parent_content_id' => $top_middle_id,
                'order' => 1,
            ));

            //Insert content
            $db->insert('engine4_core_content', array(
                'type' => 'widget',
                'name' => 'core.content',
                'page_id' => $page_id,
                'parent_content_id' => $main_middle_id,
                'order' => 1,
            ));
        }
    }
    protected function _addCreateNewStallStep2Page()
    {
        $db = $this->getDb();

        $page_id = $db->select()
            ->from('engine4_core_pages', 'page_id')
            ->where('name = ?', 'socialcommerce_stall_create-step-two')
            ->limit(1)
            ->query()
            ->fetchColumn();

        if(!$page_id) {
            $db->insert('engine4_core_pages', array(
                'name' => 'socialcommerce_stall_create-step-two',
                'displayname' => 'Social Commerce Create a New Stall',
                'title' => 'Social Commerce Create a New Stall',
                'description' => 'Social Commerce Create a New Stall',
                'custom' => 0
            ));
            $page_id = $db->lastInsertId();

            // Insert top
            $db->insert('engine4_core_content', array(
                'type' => 'container',
                'name' => 'top',
                'page_id' => $page_id,
                'order' => 1,
            ));
            $top_id = $db->lastInsertId();

            //Insert main
            $db->insert('engine4_core_content', array(
                'type' => 'container',
                'name' => 'main',
                'page_id' => $page_id,
                'order' => 2,
            ));
            $main_id = $db->lastInsertId();

            //Insert top-middle
            $db->insert('engine4_core_content', array(
                'type' => 'container',
                'name' => 'middle',
                'page_id' => $page_id,
                'parent_content_id' => $top_id,
            ));
            $top_middle_id = $db->lastInsertId();

            // Insert main-middle
            $db->insert('engine4_core_content', array(
                'type' => 'container',
                'name' => 'middle',
                'page_id' => $page_id,
                'parent_content_id' => $main_id,
                'order' => 2,
            ));
            $main_middle_id = $db->lastInsertId();

            //Insert menu
            $db->insert('engine4_core_content', array(
                'type' => 'widget',
                'name' => 'socialcommerce.main-menu',
                'page_id' => $page_id,
                'parent_content_id' => $top_middle_id,
                'order' => 1,
            ));

            //Insert content
            $db->insert('engine4_core_content', array(
                'type' => 'widget',
                'name' => 'core.content',
                'page_id' => $page_id,
                'parent_content_id' => $main_middle_id,
                'order' => 1,
            ));
        }
    }

}